Azure/BugTrackingSystem/BugTrackingSystem.Web/Controllers/FiltersController.cs
using System.Web.Mvc;

namespace BugTrackingSystem.Web.Controllers
{
    public class FiltersController : Controller
    {
        //
        // GET: /Filters/
        public ActionResult Filters()
        {
            
            return View();
        }
    }
}

Azure/BugTrackingSystem/BugTrackingSystem.Web/Controllers/HomeController.cs
using System.Web.Mvc;
using BugTrackingSystem.Service.Services;

namespace BugTrackingSystem.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IUserService _userService;

        public HomeController(IUserService userService)
        {
            _userService = userService;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Dashboard()
        {  
            return View();
        }
        public ActionResult MyProjects()
        {
            var userProjects = _userService.GetUsersProjects(1);
            return PartialView(userProjects);
        }


    }
}

Azure/BugTrackingSystem/BugTrackingSystem.Web/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BugTrackingSystem.Web.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Login()
        {
            return View();
        }

        public ActionResult ForgotPassword()
        {
            return View();
        }

        public ActionResult ResetPassword()
        {
            return View();
        }
    }
}

Azure/BugTrackingSystem/BugTrackingSystem.Web/Controllers/ProfileController.cs
using System.Web.Mvc;
using BugTrackingSystem.Service.Services;

namespace BugTrackingSystem.Web.Controllers
{
    public class ProfileController : Controller
    {

        private readonly IUserService _userService;

        public ProfileController(IUserService userService)
        {
            _userService = userService;
        }
        // GET: Profile
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult UserProjects(int userId = 1)
        {
            var projects = _userService.GetUsersProjects(userId);
            return PartialView(projects);
        }

        public ActionResult UserInfo(int userId = 1)
        {
            var user = _userService.GetUserById(userId);
            return PartialView(user);
        }
    }
}

Azure/BugTrackingSystem/BugTrackingSystem.Web/Controllers/ProjectController.cs
using System.Linq;
using System.Web.Mvc;
using BugTrackingSystem.Service.Models;
using BugTrackingSystem.Service.Models.FormModels;
using BugTrackingSystem.Service.Services;
using PagedList;

namespace BugTrackingSystem.Web.Controllers
{
    public class ProjectController : Controller
    {
        private IProjectService _projectService;
        private IUserService _userService;
        private IBugService _bugService;

        public ProjectController(IProjectService projectService, IUserService userService, IBugService bugService)
        {
            _projectService = projectService;
            _userService = userService;
            _bugService = bugService;
        }
        //
        // GET: /Project/
        [HttpGet]
        public ActionResult Project(int projectId)
        {
            var project = _projectService.GetProjectById(projectId);
            return View(project);
        }

        public ActionResult Projects(int userId = 1)
        {
            var projects = _projectService.GetAllProjects();
            return View(projects);
        }

        public ActionResult ProjectUsers()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult ProjectBugs(int projectId)
        {
            var bugs = _bugService.GetAllProjectsBugs(projectId);
            return PartialView(bugs);
        }

        public void AddProject(string name, string prefix)
        {
            _projectService.AddNewProject(name, prefix);
            RedirectToAction("Projects", "Project");
        }

        public void DeleteProject(int projectId)
        {
            _projectService.DeleteProject(projectId);
            RedirectToAction("Projects", "Project");
        }
    }
}

Azure/BugTrackingSystem/BugTrackingSystem.Web/Controllers/ProjectsController.cs
using System.Web.Mvc;

namespace BugTrackingSystem.Web.Controllers
{
    public class ProjectsController : Controller
    {
        //
        // GET: /Projects/
        public ActionResult Projects()
        {

            return View();
        }
    }
}

Azure/BugTrackingSystem/BugTrackingSystem.Web/Controllers/SearchController.cs
using System.Web.Mvc;

namespace BugTrackingSystem.Web.Controllers
{
    public class SearchController : Controller
    {
        //
        // GET: /Search/
        public ActionResult Search()
        {
            return View();
        }
    }
}

Azure/BugTrackingSystem/BugTrackingSystem.Web/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BugTrackingSystem.Service.Services;

namespace BugTrackingSystem.Web.Controllers
{
    public class SharedController : Controller
    {
        private readonly IUserService _userService;

        public SharedController(IUserService userService)
        {
            _userService = userService;
        }
        // GET: Shared
        public ActionResult UserBugs(int userId = 1)
        {
            var userBugs = _userService.GetUsersBugs(userId);
            return PartialView(userBugs);
        }

        public ActionResult Error()
        {
            return View();
        }
    }
}

Azure/BugTrackingSystem/BugTrackingSystem.Web/Controllers/TaskController.cs
using System.Web.Mvc;
using BugTrackingSystem.Service.Models;
using BugTrackingSystem.Service.Services;

namespace BugTrackingSystem.Web.Controllers
{
    public class TaskController : Controller
    {
        private readonly IBugService _bugService;

        public TaskController(IBugService bugService)
        {
            _bugService = bugService;
        }
        //
        // GET: /Task/
        public ActionResult Task(int bugId = 1)
        {
            var info = _bugService.GetFullBugById(bugId);
            //_bugService.UpdateBugPriority(1, BugPriority.Critical);
            //_bugService.UpdateBugStatus(1, BugStatus.ToDo);
            return View(info);
        }
    }
}

Azure/BugTrackingSystem/BugTrackingSystem.Web/Controllers/UsersController.cs
using System.Web.Mvc;
using BugTrackingSystem.Service.Services;

namespace BugTrackingSystem.Web.Controllers
{
    public class UsersController : Controller
    {

        //
        // GET: /Users/
        public ActionResult Users()
        {
            return View();
        }

    }
}

Azure/BugTrackingSystem/BugTrackingSystem.Web/Views/Filters/Filters.cshtml
@{
    ViewBag.Title = "Filters";
}


<div class="col-lg-12 general-container">
    <div id="header" class="row">
        <div id="headerTitle" class="col-lg-2">
            Filters
            <i class="fa fa-plus round" aria-hidden="true" data-toggle="modal" data-target="#addFilterModal"></i>
        </div>

        <div class="pull-right" id="Local-search">
            <div id="imaginary_container">
                <div class="input-group stylish-input-group">
                    <input type="text" class="form-control" placeholder="Search">
                    <span class="input-group-addon" style="background-color: #F8FEFE">
                        <a href="#">
                            <i class="glyphicon glyphicon-search" style="font-size: 18px;"></i>
                        </a>
                    </span>
                </div>
            </div>
        </div>

    </div>
    <div class="row Sort_Title_Pagination">
        <div class="dropdown" style="display: inline-block">
            <span class="sticker-properties" style="padding-right: 10px; ">Sort by:</span>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Title <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
                <li><a href="#">Project</a></li>
                <li><a href="#">Assignee</a></li>
                <li><a href="#">Status</a></li>
                <li><a href="#">Priority</a></li>
            </ul>
        </div>
        <div class=" pull-right" style="display: inline-block">
            <nav class="local-pagination">
                <ul class="pagination pagination-sm">
                    <li><a href="#">1</a></li>
                </ul>
            </nav>
        </div>
    </div>
    <div class="row">
        @for (int i = 0; i < 3; i++)
        {
            <div class="col-lg-4 col-md-4 block" id="@i" onmouseover="showCloseIcon(this)">
                <i class="fa fa-times-circle" aria-hidden="true" style="display: none;" onclick="hideFilter(this)"></i>
                <div class="custom-sticker">
                    <h4><b>Title</b></h4>
                    <div class="row">
                        <span class="col-lg-12">
                            <span class="sticker-properties">Search:</span>Search<br />
                        </span>
                        <span class="col-lg-6">
                            <span class="sticker-properties"> Status: </span>Status
                        </span>
                        <span class="col-lg-6">
                            <span class="sticker-properties"> Project: </span>Project
                        </span>
                        <span class="col-lg-6">
                            <span class="sticker-properties"> Priority: </span>BugPriority
                        </span>
                        <span class="col-lg-6">
                            <span class="sticker-properties"> Assignee: </span>AssignedUser
                        </span>
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="row Sort_Title_Pagination">
        <i class="fa fa-filter col-lg-2" aria-hidden="true" style="font-size: 18px; margin: 0; padding: 0;"> Filters: Count</i>
        <div class=" pull-right">
            <nav class="local-pagination pull-right">
                <ul class="pagination pagination-sm">
                    <li><a href="#">1</a></li>

                </ul>
            </nav>
        </div>
    </div>
</div>
<div class="modal fade" id="addFilterModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document" id="TaskModalDialog" style="padding: 0;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="fa fa-times" aria-hidden="true" style="font-size: 34px;"></i></button>
                <i class="fa fa-pencil-square-o" aria-hidden="true" style="font-size: 24px; color: white; padding: 7px 5px 0 0 "></i>
                <h3 style="display: inline-block; margin: 5px 0 0 0;">Create new filter</h3>
            </div>
            <div class="modal-body col-lg-12">
                <form>
                    <div class="form-group">
                        <input type="email" class="form-control" id="titleInput" placeholder="Title" style="margin: 0; display: inline-block">
                    </div>
                    <div class="form-group">
                        <input type="email" class="form-control" id="searchInput" placeholder="Search" style="margin: 0; display: inline-block">
                    </div>
                </form>
                <div class="col-lg-6" style="padding: 0 5px 15px 0;">
                    <select class="form-control" style="color: gray;">
                        @for (int i = 0; i < 3; i++)
                        {
                            <option>@i</option>
                        }
                    </select>
                </div>
                <div class="col-lg-6" style="padding: 0 0 15px 5px;">
                    <select class="form-control">
                        @for (int i = 0; i < 3; i++)
                        {
                            <option>@i</option>
                        }
                    </select>
                </div>
                <div class="col-lg-6" style="padding: 0 5px 15px 0;">
                    <select class="form-control">
                        @for (int i = 0; i < 3; i++)
                        {
                            <option>@i</option>
                        }
                    </select>
                </div>
                <div class="col-lg-6" style="padding: 0 0 15px 5px;">
                    <select class="form-control">
                        @for (int i = 0; i < 3; i++)
                        {
                            <option>@i</option>
                        }
                    </select>
                </div>                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn modalCreateButton">Create</button>
            </div>
        </div>
    </div>
</div>



<script>
    function hideFilter(el) {
        $(el).parent().hide();
    }
</script>

<script>
    function showCloseIcon(divId) {
        $(divId).children(".fa").show();

        $(divId).on("mouseleave", function() {
            $(divId).children(".fa").hide();
        });
    }
</script>

Azure/BugTrackingSystem/BugTrackingSystem.Web/Views/Home/Dashboard.cshtml
@model IEnumerable<BugTrackingSystem.Service.Models.BaseBugViewModel>
<body>
    <div class="general-container marginFromMenu">
        <div class="row">
            <div class="col-lg-3 padding0">
                <h1 style="margin-bottom: 40px; margin-top: 0;">My projects</h1>
                @Html.Action("MyProjects", "Home")

                <div class="container col-lg-12">
                    <a href="@Url.Action("Projects", "Project")" id="ShowAllMyProjects">Show all<i class="fa fa-long-arrow-right" aria-hidden="true"></i></a>
                </div>
            </div>

            <div class="col-lg-9" style="padding-left: 80px;">
                <h1 style="margin-bottom: 5px; margin-top: 0;">Assigned to me</h1>
                @Html.Action("UserBugs", "Shared")
            </div>
        </div>
    </div>
</body>

Azure/BugTrackingSystem/BugTrackingSystem.Web/Views/Home/Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>BugTrackingSystem</title>
    <!-- Bootstrap -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="col-lg-12" style="padding: 0 50px 0 50px; height:auto;">
        @Html.ActionLink("Filters", "Filters", "Filters")
        <br />
        @Html.ActionLink("Login", "Login", "Home")
        <br />
        @Html.ActionLink("Forgot Password", "ForgotPassword", "Home")
        <br />
        @Html.ActionLink("Reset Password", "ResetPassword", "Home")
        <br />
        @Html.ActionLink("Profile", "Index", "Profile")
        <br />
        @Html.ActionLink("Project", "Project", "Project")
        <br />
        @Html.ActionLink("Projects", "Projects", "Projects")
        <br />
        @Html.ActionLink("Search", "Search", "Search")
        <br />
        @Html.ActionLink("Users", "Users", "Users")
        <br />
        @Html.ActionLink("Task", "Task", "Task")
        <br />
        @Html.ActionLink("Dashboard", "Dashboard", "Home")
    </div>

</body>
</html>

Azure/BugTrackingSystem/BugTrackingSystem.Web/Views/Home/MyProjects.cshtml
@model IEnumerable<BugTrackingSystem.Service.Models.ProjectViewModel>
@foreach (var project in @Model)
{
    <a class="redirectAncore" href="@Url.Action("Project", "Project", new { projectId = project.ProjectId})">
        <div class="custom-sticker" style="margin-bottom: 20px;">
            <h4><b>@project.Name</b></h4>
            <div class="row">
                <span class="col-lg-12">
                    <span class="sticker-properties"> @project.Prefix </span>
                </span>
                <div class="projectInfo pull-right">
                    <i class="fa fa-pencil-square-o" aria-hidden="true" style="font-size: 15px;">@project.BugsCount</i>
                    <i class="fa fa-users" aria-hidden="true" style="font-size: 15px;">@project.UsersCount</i>
                </div>
            </div>
        </div>
    </a>
}

Azure/BugTrackingSystem/BugTrackingSystem.Web/Views/Login/ForgotPassword.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="../../Content/login_style.css">
    <title>Forget password</title>
</head>
<body>
    <div class="Login">
        <div id="logo">
            <img src="~/Content/images/logo-vertical.png" />
        </div>
        <div id="errorText">
            The email adress you entered is not registered.
        </div>
        <div id="helpText">
            If you can't access Asignar, fill in this form and an email will be <br />
            sent to you with the details to access your account again.
        </div>
        <form class="loginForm">
            <input type="text" name="email" placeholder="Email" /> <br />
            <input type="submit" value="Send" />

            <a href="#" id="hrefToLogin">Login</a>
        </form>
    </div>
</body>
</html>

Azure/BugTrackingSystem/BugTrackingSystem.Web/Views/Login/Login.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="~/Content/login_style.css">
    <title>Login</title>
</head>
<body>
    <div class="Login">
        <div id="logo">
            <img src="~/Content/images/logo-vertical.png" />
        </div>
        <div id="errorText">
            Sorry, your email or password are incorrect. Please try again.
        </div>
        <form class="loginForm">
            <input type="text" name="email" placeholder="Email" /> <br />
            <input type="password" name="password" placeholder="Password" />
            <input type="checkbox" name="RemebmerMe" />
            <span id="RememberMe">Remember me</span>
            <a id="ForgotPass" href="#">Forgot password</a>
            <input type="submit" value="Login" />
        </form>
    </div>
</body>
</html>

Azure/BugTrackingSystem/BugTrackingSystem.Web/Views/Login/ResetPassword.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="~/Content/login_style.css">
    <title>Reset password</title>
</head>
<body>
    <div class="Login">
        <div id="logo">
            <img src="~/Content/images/logo-vertical.png" />
        </div>
        <div id="resetPasswordFreeSpace">
        </div>
        <form class="loginForm">
            <input type="password" name="pass" placeholder="Password" /> <br />
            <input type="password" name="confirmPass" placeholder="Confirmation password" />
            <input type="submit" value="Reset password" />

            <a href="#" id="hrefToLogin">Login</a>
        </form>
    </div>
</body>
</html>

Azure/BugTrackingSystem/BugTrackingSystem.Web/Views/Project/ProjectUsers.cshtml
<div class="inline-block" style="padding-left: 10px;">
    <i class="fa fa-users" aria-hidden="true" style="font-size: 18px;">
        <span style="font-size: 14px;">1</span>
    </i>
</div>

Azure/BugTrackingSystem/BugTrackingSystem.Web/Views/Shared/UserBugs.cshtml
@model IEnumerable<BugTrackingSystem.Service.Models.BaseBugViewModel>
<div class="pull-right">
    <nav class="local-pagination">
        <ul class="pagination pagination-sm">
            <li><a href="#">1</a></li>
        </ul>
    </nav>
</div>
<div id="UniversalTable" class="marginFromMenu">
    @foreach (var bug in Model)
    {
        <a href="@Url.Action("Task", "Task", new {bugId = bug.BugId})" style="color: black">
            <div class="TableRow">
                <div class="TableRowInfo row">

                    <div class="IconElement inline-block pull-left padding-top7">
                        @{ var priority = String.Format("../../Content/Images/" + bug.Priority + ".png"); }
                        <img src="@priority" width="35" height="35" />
                    </div>
                    <div class="col-xs-10 padding-top7">
                        <div class="ProjectPrefix">
                            @bug.ProjectPrefix-@bug.BugId
                            @{ var status = String.Format("../../Content/Images/" + bug.Status + ".png"); }
                            <img src="@status">
                        </div>
                        <div class="ElementText">
                            @bug.Subject
                        </div>
                    </div>
                </div>
            </div>
        </a>
    }
</div>
<div class="row Sort_Title_Pagination">
    <i class="fa fa-pencil-square-o" aria-hidden="true" style="font-size: 18px;"> All my tasks: @Model.Count()</i>
    <div class=" pull-right" style="display: inline-block">
        <nav class="local-pagination">
            <ul class="pagination pagination-sm">
                <li><a href="#">1</a></li>
            </ul>
        </nav>
    </div>
</div>

Azure/BugTrackingSystem/BugTrackingSystem.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <link rel="stylesheet" href="~/Content/bootstrap.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="~/Content/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/css/bootstrap-select.min.css">
    <link rel="stylesheet" type="text/css" href="~/Content/Site.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/js/bootstrap-select.min.js"></script>
    <script>
        function showSearch() {
            $("#searchText").toggle();
        }
    </script>
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<nav>
    <div class="container-fluid">
        <div class="row">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false" style="float: right; margin: 0; height: 40px;">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar" style="background-color: #92C1BA;"></span>
                    <span class="icon-bar" style="background-color: #92C1BA;"></span>
                    <span class="icon-bar" style="background-color: #92C1BA;"></span>
                </button>
                <ul class="nav collapsed" style="display: inline-block; float: right; margin-right: 50px;">
                    <li class="dropdown userProfile" id="userCol">
                        <a href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style="padding: 5px; background-color: #4D868D; color: white">
                            <img src="~/Content/Images/orwell.jpeg" class="img-circle" style="height: 30px; width: 30px; margin-right: 5px;"/>
                        </a>
                        <ul class="dropdown-menu dropdown-toggle" style="margin-right: 40px;">
                            <li style="padding-left: 10px; margin-top: -6px; height: 16px; display: list-item;"><span class="glyphicon glyphicon-triangle-top" style="font-size: 20px; color: #92C1BA; background-color: transparent;"></span></li>
                            <li><a href="#">Profile</a></li>
                            <li><a href="#">Sign Out</a></li>
                        </ul>
                    </li>
                </ul>
                <a href="@Url.Action("Dashboard", "Home")" class="navbar-brand logo" style="padding: 4px 0px 4px 30px; height: 40px;">
                    <img src="~/Content/Images/logo.png" alt="logo">
                </a>
            </div>
            <div class="collapse navbar-collapse div-col" id="bs-example-navbar-collapse-1" style="margin-bottom: 1px;">
                <ul class="menu navbar-nav" style="z-index: 0;">
                    <li class="li-mobile"><a href="@Url.Action("Projects", "Project")">Projects</a></li>
                    <li class="li-mobile"><a href="@Url.Action("Filters", "Filters")">Filters</a></li>
                    <li id="liTask" class="li-mobile"><a href="#">Create task</a></li>
                    <li id="liSearch" class="li-mobile"><a href="#">Search</a></li>
                </ul>
                <button type="button" class="btn btn-header" id="taskButton" aria-label="Left Align" data-toggle="modal" data-target="#createNewTask">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true" style="color: white;"></span>
                    Create task
                </button>

                <ul class="nav navbar-nav navbar-right" id="userDrop" style="margin-top: 0; margin-left: 25px; margin-right: 25px;">
                    <li class="dropdown userProfile">
                        <a href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style="padding: 5px; background-color: #4D868D; color: white">
                            <img src="~/Content/Images/orwell.jpeg" class="img-circle" style="height: 30px; width: 30px; margin-right: 5px;"/>
                            George Orwell
                        </a>
                        <ul class="dropdown-menu dropdown-toggle" style="box-shadow: none; margin-top: -1px; padding: 0; border: 0; border-radius: 0;">
                            <li style="background-color: transparent; padding-left: 200px; margin-top: -16px; height: 16px; display: list-item; background-color: transparent;"><span class="glyphicon glyphicon-triangle-top" style="font-size: 20px; color: #92C1BA; line-height: 20px; margin-left: -30px;"></span></li>
                            <li style="height: 40px;"><a style="height: 40px; padding-top: 10px; color: white;" class="userProfile" href="@Url.Action("Index", "Profile")">Profile</a></li>
                            <li style="height: 40px;"><a style="height: 40px; padding-top: 10px; color: white;" class="userProfile" href="@Url.Action("Login", "Login")">Sign Out</a></li>
                        </ul>
                    </li>
                </ul>
                <div class="nav navbar-nav navbar-right" id="search">
                    <form class="navbar-form navbar-left" role="search" style="padding: 0">
                        <div class="form-group" style="display: none; height: 25px; margin-top: -25px;" id="searchText">
                            <input type="text" class="form-control" style="background-color: #4D868D; border-radius: 0; height: 28px; margin-top: 4px;" placeholder="Search">
                        </div>
                        <span class="glyphicon glyphicon-search" style="font-size: 20px; color: white; line-height: 20px; margin-left: -30px;" onclick="showSearch()"></span>
                    </form>
                </div>
            </div>
        </div>
    </div>
</nav>

    <div class="modal fade" id="createNewTask" tabindex="-1" role="dialog" aria-labelledby="createNewTaskLabel">
        <div class="modal-dialog" role="document" id="TaskModalDialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="fa fa-times" aria-hidden="true" style="font-size: 34px;"></i></button>
                    <i class="fa fa-pencil-square-o" aria-hidden="true" style="font-size: 24px; color: white; padding: 7px 5px 0 0 "></i>
                    <h3 style="display: inline-block; margin: 5px 0 0 0;">Create new task</h3>
                </div>
                <div class="modal-body col-lg-12">
                    <form>
                        <div class="form-group">
                            <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Title" style="margin: 0; display: inline-block">
                        </div>
                    </form>
                    <div class="col-lg-6" style="padding: 0 5px 15px 0;">
                        <select class="form-control" style="color: gray;">
                            @for (int i = 0; i < 3; i++)
                            {
                                <option>@i</option>
                            }
                        </select>
                    </div>
                    <div class="col-lg-6" style="padding: 0 0 15px 5px;">
                        <select class="form-control">
                            <option selected="selected">Owner</option>
                            @for (int i = 0; i < 3; i++)
                            {
                                <option>@i</option>
                            }
                        </select>
                    </div>
                    <div class="col-lg-6" style="padding: 0 5px 15px 0;">
                        <select class="form-control">
                            @for (int i = 0; i < 3; i++)
                            {
                                <option>@i</option>
                            }
                        </select>
                    </div>
                    <div class="col-lg-6" style="padding: 0 0 15px 5px;">
                        <select class="form-control">
                            @for (int i = 0; i < 3; i++)
                            {
                                <option>@i</option>
                            } 
                        </select>
                    </div>
                    <form>
                        <textarea class="form-control" placeholder="Description" rows="5" ></textarea>
                    </form>
                </div>
                <div class="modal-footer">
                    <div class="pull-left">
                        <b>Attachments</b>
                        <i class="fa fa-plus round" aria-hidden="true" style="font-size: 15px;"></i>
                    </div>
                    <button type="button" class="btn modalCreateButton" style="margin-top: 50px;">Create</button>
                </div>
            </div>
        </div>
    </div>

@RenderBody()

</body>
</html>